"""add user model

Revision ID: c491dbc90a5d
Revises: 8632e8da17a6
Create Date: 2026-08-27 19:20:10.995861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c491dbc90a5d'
down_revision: Union[str, Sequence[str], None] = '8632e8da17a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.add_column('urls', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_urls_user_id_original_url'), 'urls', ['user_id', 'original_url'])
    op.create_foreign_key(op.f('fk_urls_user_id_users'), 'urls', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_urls_user_id_users'), 'urls', type_='foreignkey')
    op.drop_constraint(op.f('uq_urls_user_id_original_url'), 'urls', type_='unique')
    op.drop_column('urls', 'user_id')
    op.drop_table('users')
    # ### end Alembic commands ###
